# Generated by Django 5.1.7 on 2025-04-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('tracking_number', models.CharField(max_length=15)),
                ('shipping_status', models.CharField(max_length=20)),
                ('last_updated', models.DateField()),
            ],
            options={
                'db_table': 'shippings',
                'managed': False,
            },
        ),
    ]
