# Generated by Django 5.1.7 on 2025-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('procurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('In transit', 'In transit'), ('Processing', 'Processing')], default='Processing', max_length=20)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procurements',
                'managed': False,
            },
        ),
    ]
