# Generated by Django 5.1.7 on 2025-04-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_procurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('On the way', 'On the way'), ('Completed', 'Completed')], default='Pending', max_length=15)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
